export const uploadConstants = {
    GET_IMAGES_REQUEST: 'GET_IMAGES_REQUEST',
    GET_IMAGES_SUCCESS: 'GET_IMAGES_SUCCESS',
    GET_IMAGES_FAILURE: 'GET_IMAGES_FAILURE',
    IMAGE_UPLOAD_REQUEST: 'IMAGE_UPLOAD_REQUEST',
    IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
    IMAGE_UPLOAD_FAILURE: 'IMAGE_UPLOAD_FAILURE',
}